"""GENERIERT — NICHT MANUELL EDITIEREN.

Quellen:
  - OSV (https://osv.dev) — Apache 2.0
  - CISA Known Exploited Vulnerabilities (KEV)

Generator: scripts/sync-known-vuln-builds.py
Stand:    2026-05-08 15:48 UTC

Filter: KEV-listed CVEs ODER CVSS >= 9.0. Manuelle Eintraege in
`reporter/eol_detector.py:KNOWN_VULN_BUILDS_MANUAL` haben Vorrang.

Audit-Eintrag: docs/scan-flow/Scan-Optimierung.md Sektion 3.11.4
(F-RPT-001).
"""

from __future__ import annotations

# (vendor, product, version_prefix) -> info dict
KNOWN_VULN_BUILDS_GENERATED: dict[tuple[str, str, str], dict] = {
    ("apache", "httpd", "<10.2.1.14-75sv"): {"_source": "osv+kev", "cves": ["CVE-2024-38475"], "name": "Apache HTTP Server Improper Escaping of Output Vulnerability", "severity": "CRITICAL"},
    ("apache", "httpd", "<2.4.60"): {"_source": "osv+kev", "cves": ["CVE-2024-38475"], "name": "Apache HTTP Server Improper Escaping of Output Vulnerability", "severity": "CRITICAL"},
    ("apache", "httpd", "<=14.04"): {"_source": "osv+kev", "cves": ["CVE-2019-0211"], "name": "Apache HTTP Server Privilege Escalation Vulnerability", "severity": "CRITICAL"},
    ("apache", "httpd", "<=16.04"): {"_source": "osv+kev", "cves": ["CVE-2019-0211"], "name": "Apache HTTP Server Privilege Escalation Vulnerability", "severity": "CRITICAL"},
    ("apache", "httpd", "<=17.1"): {"_source": "osv+kev", "cves": ["CVE-2021-42013", "CVE-2021-41773"], "name": "Apache HTTP Server Path Traversal Vulnerability", "severity": "CRITICAL"},
    ("apache", "httpd", "<=17.2"): {"_source": "osv+kev", "cves": ["CVE-2021-42013", "CVE-2021-41773"], "name": "Apache HTTP Server Path Traversal Vulnerability", "severity": "CRITICAL"},
    ("apache", "httpd", "<=2.4.38"): {"_source": "osv+kev", "cves": ["CVE-2019-0211"], "name": "Apache HTTP Server Privilege Escalation Vulnerability", "severity": "CRITICAL"},
    ("apache", "httpd", "<=2.4.49"): {"_source": "osv+kev", "cves": ["CVE-2021-42013", "CVE-2021-41773"], "name": "Apache HTTP Server Path Traversal Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "bitbucket", "<7.17.10"): {"_source": "osv+kev", "cves": ["CVE-2022-36804"], "name": "Atlassian Bitbucket Server and Data Center Command Injection Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "bitbucket", "<7.21.4"): {"_source": "osv+kev", "cves": ["CVE-2022-36804"], "name": "Atlassian Bitbucket Server and Data Center Command Injection Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "bitbucket", "<7.6.17"): {"_source": "osv+kev", "cves": ["CVE-2022-36804"], "name": "Atlassian Bitbucket Server and Data Center Command Injection Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<6.12.3"): {"_source": "osv+kev", "cves": ["CVE-2019-3396"], "name": "Atlassian Confluence Server and Data Center Server-Side Template Injection Vulne", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<6.12.4"): {"_source": "osv+kev", "cves": ["CVE-2019-3398"], "name": "Atlassian Confluence Server and Data Center Path Traversal Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<6.13.23"): {"_source": "osv+kev", "cves": ["CVE-2021-26084"], "name": "Atlassian Confluence Server and Data Center Object-Graph Navigation Language (OG", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<6.13.3"): {"_source": "osv+kev", "cves": ["CVE-2019-3396"], "name": "Atlassian Confluence Server and Data Center Server-Side Template Injection Vulne", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<6.13.4"): {"_source": "osv+kev", "cves": ["CVE-2019-3398"], "name": "Atlassian Confluence Server and Data Center Path Traversal Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<6.6.12"): {"_source": "osv+kev", "cves": ["CVE-2019-3396"], "name": "Atlassian Confluence Server and Data Center Server-Side Template Injection Vulne", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<6.6.13"): {"_source": "osv+kev", "cves": ["CVE-2019-3398"], "name": "Atlassian Confluence Server and Data Center Path Traversal Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<7.11.6"): {"_source": "osv+kev", "cves": ["CVE-2021-26084"], "name": "Atlassian Confluence Server and Data Center Object-Graph Navigation Language (OG", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<7.12.3"): {"_source": "osv+kev", "cves": ["CVE-2021-26085"], "name": "Atlassian Confluence Server Pre-Authorization Arbitrary File Read Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<7.13.7"): {"_source": "osv+kev", "cves": ["CVE-2022-26134"], "name": "Atlassian Confluence Server and Data Center Remote Code Execution Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<7.14.3"): {"_source": "osv+kev", "cves": ["CVE-2022-26134"], "name": "Atlassian Confluence Server and Data Center Remote Code Execution Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<7.19.16"): {"_source": "osv+kev", "cves": ["CVE-2023-22518"], "name": "Atlassian Confluence Data Center and Server Improper Authorization Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<7.4.10"): {"_source": "osv+kev", "cves": ["CVE-2021-26085"], "name": "Atlassian Confluence Server Pre-Authorization Arbitrary File Read Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<7.4.11"): {"_source": "osv+kev", "cves": ["CVE-2021-26084"], "name": "Atlassian Confluence Server and Data Center Object-Graph Navigation Language (OG", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<7.4.17"): {"_source": "osv+kev", "cves": ["CVE-2022-26134"], "name": "Atlassian Confluence Server and Data Center Remote Code Execution Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<8.3.3"): {"_source": "osv+kev", "cves": ["CVE-2023-22515"], "name": "Atlassian Confluence Data Center and Server Broken Access Control Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<8.3.4"): {"_source": "osv+kev", "cves": ["CVE-2023-22518"], "name": "Atlassian Confluence Data Center and Server Improper Authorization Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<8.4.3"): {"_source": "osv+kev", "cves": ["CVE-2023-22515"], "name": "Atlassian Confluence Data Center and Server Broken Access Control Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<8.4.4"): {"_source": "osv+kev", "cves": ["CVE-2023-22518"], "name": "Atlassian Confluence Data Center and Server Improper Authorization Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<8.5.2"): {"_source": "osv+kev", "cves": ["CVE-2023-22515"], "name": "Atlassian Confluence Data Center and Server Broken Access Control Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<8.5.4"): {"_source": "osv+kev", "cves": ["CVE-2023-22527"], "name": "Atlassian Confluence Data Center and Server Template Injection Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<=2.7.34"): {"_source": "osv+kev", "cves": ["CVE-2022-26138"], "name": "Atlassian Questions For Confluence App Hard-coded Credentials Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<=2.7.35"): {"_source": "osv+kev", "cves": ["CVE-2022-26138"], "name": "Atlassian Questions For Confluence App Hard-coded Credentials Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<=3.0.2"): {"_source": "osv+kev", "cves": ["CVE-2022-26138"], "name": "Atlassian Questions For Confluence App Hard-coded Credentials Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "confluence", "<=8.7.0"): {"_source": "osv+kev", "cves": ["CVE-2023-22527"], "name": "Atlassian Confluence Data Center and Server Template Injection Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "jira", "<7.13.5"): {"_source": "osv+kev", "cves": ["CVE-2019-11581"], "name": "Atlassian Jira Server and Data Center Server-Side Template Injection Vulnerabili", "severity": "CRITICAL"},
    ("atlassian", "jira", "<7.6.14"): {"_source": "osv+kev", "cves": ["CVE-2019-11581"], "name": "Atlassian Jira Server and Data Center Server-Side Template Injection Vulnerabili", "severity": "CRITICAL"},
    ("atlassian", "jira", "<8.0.3"): {"_source": "osv+kev", "cves": ["CVE-2019-11581"], "name": "Atlassian Jira Server and Data Center Server-Side Template Injection Vulnerabili", "severity": "CRITICAL"},
    ("atlassian", "jira", "<8.13.6"): {"_source": "osv+kev", "cves": ["CVE-2021-26086"], "name": "Atlassian Jira Server and Data Center Path Traversal Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "jira", "<8.16.1"): {"_source": "osv+kev", "cves": ["CVE-2021-26086"], "name": "Atlassian Jira Server and Data Center Path Traversal Vulnerability", "severity": "CRITICAL"},
    ("atlassian", "jira", "<8.5.14"): {"_source": "osv+kev", "cves": ["CVE-2021-26086"], "name": "Atlassian Jira Server and Data Center Path Traversal Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<10.5-70.18"): {"_source": "osv+kev", "cves": ["CVE-2020-8193", "CVE-2020-8195", "CVE-2020-8196"], "name": "Citrix ADC, Gateway, and SD-WAN WANOP Appliance Authorization Bypass Vulnerabili", "severity": "CRITICAL"},
    ("citrix", "adc", "<11.1-64.14"): {"_source": "osv+kev", "cves": ["CVE-2020-8193", "CVE-2020-8195", "CVE-2020-8196"], "name": "Citrix ADC, Gateway, and SD-WAN WANOP Appliance Authorization Bypass Vulnerabili", "severity": "CRITICAL"},
    ("citrix", "adc", "<12.0-63.21"): {"_source": "osv+kev", "cves": ["CVE-2020-8193", "CVE-2020-8195", "CVE-2020-8196"], "name": "Citrix ADC, Gateway, and SD-WAN WANOP Appliance Authorization Bypass Vulnerabili", "severity": "CRITICAL"},
    ("citrix", "adc", "<12.1-55.291"): {"_source": "osv+kev", "cves": ["CVE-2022-27518"], "name": "Citrix Application Delivery Controller (ADC) and Gateway Authentication Bypass V", "severity": "CRITICAL"},
    ("citrix", "adc", "<12.1-55.297"): {"_source": "osv+kev", "cves": ["CVE-2023-3519"], "name": "Citrix NetScaler ADC and NetScaler Gateway Code Injection Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<12.1-55.300"): {"_source": "osv+kev", "cves": ["CVE-2023-4966"], "name": "Citrix NetScaler ADC and NetScaler Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<12.1-55.302"): {"_source": "osv+kev", "cves": ["CVE-2023-6549", "CVE-2023-6548"], "name": "Citrix NetScaler ADC and NetScaler Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<12.1-55.328"): {"_source": "osv+kev", "cves": ["CVE-2025-5777"], "name": "Citrix NetScaler ADC and Gateway Out-of-Bounds Read Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<12.1-65.25"): {"_source": "osv+kev", "cves": ["CVE-2022-27518"], "name": "Citrix Application Delivery Controller (ADC) and Gateway Authentication Bypass V", "severity": "CRITICAL"},
    ("citrix", "adc", "<13.0-58.32"): {"_source": "osv+kev", "cves": ["CVE-2022-27518"], "name": "Citrix Application Delivery Controller (ADC) and Gateway Authentication Bypass V", "severity": "CRITICAL"},
    ("citrix", "adc", "<13.0-91.13"): {"_source": "osv+kev", "cves": ["CVE-2023-3519"], "name": "Citrix NetScaler ADC and NetScaler Gateway Code Injection Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<13.0-92.19"): {"_source": "osv+kev", "cves": ["CVE-2023-4966"], "name": "Citrix NetScaler ADC and NetScaler Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<13.0-92.21"): {"_source": "osv+kev", "cves": ["CVE-2023-6549", "CVE-2023-6548"], "name": "Citrix NetScaler ADC and NetScaler Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<13.1-37.159"): {"_source": "osv+kev", "cves": ["CVE-2023-3519"], "name": "Citrix NetScaler ADC and NetScaler Gateway Code Injection Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<13.1-37.164"): {"_source": "osv+kev", "cves": ["CVE-2023-4966"], "name": "Citrix NetScaler ADC and NetScaler Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<13.1-37.176"): {"_source": "osv+kev", "cves": ["CVE-2023-6549", "CVE-2023-6548"], "name": "Citrix NetScaler ADC and NetScaler Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<13.1-37.235"): {"_source": "osv+kev", "cves": ["CVE-2025-5777"], "name": "Citrix NetScaler ADC and Gateway Out-of-Bounds Read Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<13.1-37.236"): {"_source": "osv+kev", "cves": ["CVE-2025-6543"], "name": "Citrix NetScaler ADC and Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<13.1-58.32"): {"_source": "osv+kev", "cves": ["CVE-2025-5777"], "name": "Citrix NetScaler ADC and Gateway Out-of-Bounds Read Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<13.1-59.19"): {"_source": "osv+kev", "cves": ["CVE-2025-6543"], "name": "Citrix NetScaler ADC and Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<14.1-47.46"): {"_source": "osv+kev", "cves": ["CVE-2025-6543"], "name": "Citrix NetScaler ADC and Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<=10.5"): {"_source": "osv+kev", "cves": ["CVE-2019-19781"], "name": "Citrix ADC, Gateway, and SD-WAN WANOP Appliance Code Execution Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<=11.1"): {"_source": "osv+kev", "cves": ["CVE-2019-19781"], "name": "Citrix ADC, Gateway, and SD-WAN WANOP Appliance Code Execution Vulnerability", "severity": "CRITICAL"},
    ("citrix", "adc", "<=12.0"): {"_source": "osv+kev", "cves": ["CVE-2019-19781"], "name": "Citrix ADC, Gateway, and SD-WAN WANOP Appliance Code Execution Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<10.0.8"): {"_source": "osv+kev", "cves": ["CVE-2019-12991", "CVE-2019-12989"], "name": "Citrix SD-WAN and NetScaler Command Injection Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<10.2.3"): {"_source": "osv+kev", "cves": ["CVE-2019-12991", "CVE-2019-12989"], "name": "Citrix SD-WAN and NetScaler Command Injection Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<12.1-55.297"): {"_source": "osv+kev", "cves": ["CVE-2023-3519"], "name": "Citrix NetScaler ADC and NetScaler Gateway Code Injection Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<12.1-55.300"): {"_source": "osv+kev", "cves": ["CVE-2023-4966"], "name": "Citrix NetScaler ADC and NetScaler Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<12.1-55.302"): {"_source": "osv+kev", "cves": ["CVE-2023-6549", "CVE-2023-6548"], "name": "Citrix NetScaler ADC and NetScaler Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<12.1-55.328"): {"_source": "osv+kev", "cves": ["CVE-2025-5777"], "name": "Citrix NetScaler ADC and Gateway Out-of-Bounds Read Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<12.1-55.330"): {"_source": "osv+kev", "cves": ["CVE-2025-7775"], "name": "Citrix NetScaler Memory Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<13.0-91.13"): {"_source": "osv+kev", "cves": ["CVE-2023-3519"], "name": "Citrix NetScaler ADC and NetScaler Gateway Code Injection Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<13.0-92.19"): {"_source": "osv+kev", "cves": ["CVE-2023-4966"], "name": "Citrix NetScaler ADC and NetScaler Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<13.0-92.21"): {"_source": "osv+kev", "cves": ["CVE-2023-6549", "CVE-2023-6548"], "name": "Citrix NetScaler ADC and NetScaler Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<13.1-37.159"): {"_source": "osv+kev", "cves": ["CVE-2023-3519"], "name": "Citrix NetScaler ADC and NetScaler Gateway Code Injection Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<13.1-37.164"): {"_source": "osv+kev", "cves": ["CVE-2023-4966"], "name": "Citrix NetScaler ADC and NetScaler Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<13.1-37.176"): {"_source": "osv+kev", "cves": ["CVE-2023-6549", "CVE-2023-6548"], "name": "Citrix NetScaler ADC and NetScaler Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<13.1-37.235"): {"_source": "osv+kev", "cves": ["CVE-2025-5777"], "name": "Citrix NetScaler ADC and Gateway Out-of-Bounds Read Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<13.1-37.236"): {"_source": "osv+kev", "cves": ["CVE-2025-6543"], "name": "Citrix NetScaler ADC and Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<13.1-37.241"): {"_source": "osv+kev", "cves": ["CVE-2025-7775"], "name": "Citrix NetScaler Memory Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<13.1-58.32"): {"_source": "osv+kev", "cves": ["CVE-2025-5777"], "name": "Citrix NetScaler ADC and Gateway Out-of-Bounds Read Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<13.1-59.19"): {"_source": "osv+kev", "cves": ["CVE-2025-6543"], "name": "Citrix NetScaler ADC and Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<13.1-59.22"): {"_source": "osv+kev", "cves": ["CVE-2025-7775"], "name": "Citrix NetScaler Memory Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<14.1-47.46"): {"_source": "osv+kev", "cves": ["CVE-2025-6543"], "name": "Citrix NetScaler ADC and Gateway Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("citrix", "netscaler", "<=9.1.2.26.561201"): {"_source": "osv+kev", "cves": ["CVE-2017-6316"], "name": "Citrix Multiple Products Remote Code Execution Vulnerability", "severity": "CRITICAL"},
    ("connectwise", "screenconnect", "<23.9.8"): {"_source": "osv+kev", "cves": ["CVE-2024-1708", "CVE-2024-1709"], "name": "ConnectWise ScreenConnect Path Traversal Vulnerability", "severity": "CRITICAL"},
    ("connectwise", "screenconnect", "<25.2.4"): {"_source": "osv+kev", "cves": ["CVE-2025-3935"], "name": "ConnectWise ScreenConnect Improper Authentication Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<1.2.9"): {"_source": "osv+kev", "cves": ["CVE-2018-13382", "CVE-2018-13383"], "name": "Fortinet FortiOS and FortiProxy Improper Authorization", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<2.0.14"): {"_source": "osv+kev", "cves": ["CVE-2024-21762"], "name": "Fortinet FortiOS Out-of-Bound Write Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<5.2.15"): {"_source": "osv+kev", "cves": ["CVE-2018-13383"], "name": "Fortinet FortiOS and FortiProxy Out-of-bounds Write", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<5.4.11"): {"_source": "osv+kev", "cves": ["CVE-2018-13382"], "name": "Fortinet FortiOS and FortiProxy Improper Authorization", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<5.4.5"): {"_source": "osv+kev", "cves": ["CVE-2018-13374"], "name": "Fortinet FortiOS and FortiADC Improper Access Control Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<6.0.10"): {"_source": "osv+kev", "cves": ["CVE-2020-12812"], "name": "Fortinet FortiOS SSL VPN Improper Authentication Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<6.0.14"): {"_source": "osv+kev", "cves": ["CVE-2021-44168"], "name": "Fortinet FortiOS Arbitrary File Download", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<6.0.2"): {"_source": "osv+kev", "cves": ["CVE-2018-13374"], "name": "Fortinet FortiOS and FortiADC Improper Access Control Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<6.2.10"): {"_source": "osv+kev", "cves": ["CVE-2021-44168"], "name": "Fortinet FortiOS Arbitrary File Download", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<6.2.14"): {"_source": "osv+kev", "cves": ["CVE-2022-41328"], "name": "Fortinet FortiOS Path Traversal Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<6.2.4"): {"_source": "osv+kev", "cves": ["CVE-2020-12812"], "name": "Fortinet FortiOS SSL VPN Improper Authentication Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<6.4.12"): {"_source": "osv+kev", "cves": ["CVE-2022-41328"], "name": "Fortinet FortiOS Path Traversal Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<6.4.8"): {"_source": "osv+kev", "cves": ["CVE-2021-44168"], "name": "Fortinet FortiOS Arbitrary File Download", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<7.0.15"): {"_source": "osv+kev", "cves": ["CVE-2024-21762"], "name": "Fortinet FortiOS Out-of-Bound Write Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<7.0.17"): {"_source": "osv+kev", "cves": ["CVE-2025-24472", "CVE-2024-55591"], "name": "Fortinet FortiOS and FortiProxy Authentication Bypass Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<7.0.20"): {"_source": "osv+kev", "cves": ["CVE-2025-24472", "CVE-2024-55591"], "name": "Fortinet FortiOS and FortiProxy Authentication Bypass Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<7.2.13"): {"_source": "osv+kev", "cves": ["CVE-2025-24472", "CVE-2024-55591"], "name": "Fortinet FortiOS and FortiProxy Authentication Bypass Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<7.2.9"): {"_source": "osv+kev", "cves": ["CVE-2024-21762"], "name": "Fortinet FortiOS Out-of-Bound Write Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<=1.1.6"): {"_source": "osv+kev", "cves": ["CVE-2023-27997"], "name": "Fortinet FortiOS and FortiProxy SSL-VPN Heap-Based Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<=1.2.13"): {"_source": "osv+kev", "cves": ["CVE-2023-27997"], "name": "Fortinet FortiOS and FortiProxy SSL-VPN Heap-Based Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<=2.0.0"): {"_source": "osv+kev", "cves": ["CVE-2018-13382", "CVE-2018-13383"], "name": "Fortinet FortiOS and FortiProxy Improper Authorization", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<=2.0.12"): {"_source": "osv+kev", "cves": ["CVE-2023-27997"], "name": "Fortinet FortiOS and FortiProxy SSL-VPN Heap-Based Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<=5.0.14"): {"_source": "osv+kev", "cves": ["CVE-2022-42475"], "name": "Fortinet FortiOS Heap-Based Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<=5.2.15"): {"_source": "osv+kev", "cves": ["CVE-2022-42475"], "name": "Fortinet FortiOS Heap-Based Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<=5.4.13"): {"_source": "osv+kev", "cves": ["CVE-2022-42475"], "name": "Fortinet FortiOS Heap-Based Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<=5.6.10"): {"_source": "osv+kev", "cves": ["CVE-2019-6693"], "name": "Fortinet FortiOS Use of Hard-Coded Credentials Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<=6.0.16"): {"_source": "osv+kev", "cves": ["CVE-2022-41328"], "name": "Fortinet FortiOS Path Traversal Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<=6.0.6"): {"_source": "osv+kev", "cves": ["CVE-2019-6693"], "name": "Fortinet FortiOS Use of Hard-Coded Credentials Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<=6.1.0"): {"_source": "osv+kev", "cves": ["CVE-2018-13374"], "name": "Fortinet FortiOS and FortiADC Improper Access Control Vulnerability", "severity": "CRITICAL"},
    ("fortinet", "fortigate", "<=6.2.0"): {"_source": "osv+kev", "cves": ["CVE-2019-6693", "CVE-2019-5591"], "name": "Fortinet FortiOS Use of Hard-Coded Credentials Vulnerability", "severity": "CRITICAL"},
    ("gitlab", "", "<13.6.7"): {"_source": "osv+kev", "cves": ["CVE-2021-22175"], "name": "GitLab Server-Side Request Forgery (SSRF) Vulnerability", "severity": "CRITICAL"},
    ("gitlab", "", "<13.8.8"): {"_source": "osv+kev", "cves": ["CVE-2021-22205"], "name": "GitLab Community and Enterprise Editions Remote Code Execution Vulnerability", "severity": "CRITICAL"},
    ("gitlab", "", "<14.3.6"): {"_source": "osv+kev", "cves": ["CVE-2021-39935"], "name": "GitLab Community and Enterprise Editions Server-Side Request Forgery (SSRF) Vuln", "severity": "CRITICAL"},
    ("gitlab", "", "<16.1.6"): {"_source": "osv+kev", "cves": ["CVE-2023-7028"], "name": "Weak Password Recovery Mechanism for Forgotten Password in GitLab", "severity": "CRITICAL"},
    ("gitlab", "", "<16.2.9"): {"_source": "osv+kev", "cves": ["CVE-2023-7028"], "name": "Weak Password Recovery Mechanism for Forgotten Password in GitLab", "severity": "CRITICAL"},
    ("gitlab", "", "<16.3.7"): {"_source": "osv+kev", "cves": ["CVE-2023-7028"], "name": "Weak Password Recovery Mechanism for Forgotten Password in GitLab", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<22.7"): {"_source": "osv+kev", "cves": ["CVE-2025-22457"], "name": "Ivanti Connect Secure, Policy Secure, and ZTA Gateways Stack-Based Buffer Overfl", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=22.7-NA"): {"_source": "osv+kev", "cves": ["CVE-2025-22457"], "name": "Ivanti Connect Secure, Policy Secure, and ZTA Gateways Stack-Based Buffer Overfl", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=22.7-r1"): {"_source": "osv+kev", "cves": ["CVE-2025-22457"], "name": "Ivanti Connect Secure, Policy Secure, and ZTA Gateways Stack-Based Buffer Overfl", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=22.7-r2"): {"_source": "osv+kev", "cves": ["CVE-2025-0282"], "name": "Ivanti Connect Secure, Policy Secure, and ZTA Gateways Stack-Based Buffer Overfl", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=22.7-r2\\.1"): {"_source": "osv+kev", "cves": ["CVE-2025-0282"], "name": "Ivanti Connect Secure, Policy Secure, and ZTA Gateways Stack-Based Buffer Overfl", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=22.7-r2\\.2"): {"_source": "osv+kev", "cves": ["CVE-2025-0282"], "name": "Ivanti Connect Secure, Policy Secure, and ZTA Gateways Stack-Based Buffer Overfl", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=8.1-NA"): {"_source": "osv+kev", "cves": ["CVE-2019-11539"], "name": "Ivanti Pulse Connect Secure and Policy Secure Command Injection Vulnerability", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=8.1-r1\\.0"): {"_source": "osv+kev", "cves": ["CVE-2019-11539"], "name": "Ivanti Pulse Connect Secure and Policy Secure Command Injection Vulnerability", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=8.1-r1\\.1"): {"_source": "osv+kev", "cves": ["CVE-2019-11539"], "name": "Ivanti Pulse Connect Secure and Policy Secure Command Injection Vulnerability", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=8.2-r10\\.0"): {"_source": "osv+kev", "cves": ["CVE-2019-11510"], "name": "Ivanti Pulse Connect Secure Arbitrary File Read Vulnerability", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=8.2-r1\\.0"): {"_source": "osv+kev", "cves": ["CVE-2019-11510"], "name": "Ivanti Pulse Connect Secure Arbitrary File Read Vulnerability", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=8.2-r1\\.1"): {"_source": "osv+kev", "cves": ["CVE-2019-11510"], "name": "Ivanti Pulse Connect Secure Arbitrary File Read Vulnerability", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=9.0"): {"_source": "osv+kev", "cves": ["CVE-2023-46805", "CVE-2024-21887", "CVE-2020-8243", "CVE-2020-8260"], "name": "Ivanti Connect Secure and Policy Secure Authentication Bypass Vulnerability", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=9.0-NA"): {"_source": "osv+kev", "cves": ["CVE-2024-21893", "CVE-2021-22893", "CVE-2021-22900", "CVE-2021-22894", "CVE-2021-22899"], "name": "Ivanti Connect Secure, Policy Secure, and Neurons Server-Side Request Forgery (S", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=9.0-r1"): {"_source": "osv+kev", "cves": ["CVE-2024-21893", "CVE-2021-22893", "CVE-2021-22900", "CVE-2021-22894", "CVE-2021-22899"], "name": "Ivanti Connect Secure, Policy Secure, and Neurons Server-Side Request Forgery (S", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=9.0-r1\\.0"): {"_source": "osv+kev", "cves": ["CVE-2021-22900", "CVE-2021-22894", "CVE-2021-22899"], "name": "Ivanti Pulse Connect Secure Unrestricted File Upload Vulnerability", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=9.0-r2"): {"_source": "osv+kev", "cves": ["CVE-2024-21893", "CVE-2021-22893"], "name": "Ivanti Connect Secure, Policy Secure, and Neurons Server-Side Request Forgery (S", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=9.1-NA"): {"_source": "osv+kev", "cves": ["CVE-2020-8243", "CVE-2020-8260"], "name": "Ivanti Pulse Connect Secure Code Execution Vulnerability", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=9.1-r1"): {"_source": "osv+kev", "cves": ["CVE-2023-46805", "CVE-2024-21887", "CVE-2020-8243"], "name": "Ivanti Connect Secure and Policy Secure Authentication Bypass Vulnerability", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=9.1-r10"): {"_source": "osv+kev", "cves": ["CVE-2023-46805", "CVE-2024-21887"], "name": "Ivanti Connect Secure and Policy Secure Authentication Bypass Vulnerability", "severity": "CRITICAL"},
    ("ivanti", "connect-secure", "<=9.1-r1\\.0"): {"_source": "osv+kev", "cves": ["CVE-2020-8260"], "name": "Ivanti Pulse Connect Secure Code Execution Vulnerability", "severity": "CRITICAL"},
    ("jetbrains", "teamcity", "<2023.05.4"): {"_source": "osv+kev", "cves": ["CVE-2023-42793"], "name": "JetBrains TeamCity Authentication Bypass Vulnerability", "severity": "CRITICAL"},
    ("jetbrains", "teamcity", "<2023.11.4"): {"_source": "osv+kev", "cves": ["CVE-2024-27199", "CVE-2024-27198"], "name": "JetBrains TeamCity Relative Path Traversal Vulnerability", "severity": "CRITICAL"},
    ("microsoft", "iis", "<=6.0"): {"_source": "osv+kev", "cves": ["CVE-2017-7269"], "name": "Microsoft Windows Server Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("php", "", "<3.2.4"): {"_source": "osv+kev", "cves": ["CVE-2019-9082"], "name": "ThinkPHP Remote Code Execution Vulnerability", "severity": "CRITICAL"},
    ("php", "", "<5.2.18"): {"_source": "osv+kev", "cves": ["CVE-2016-10033"], "name": "PHPMailer Command Injection Vulnerability", "severity": "CRITICAL"},
    ("php", "", "<5.6.3"): {"_source": "osv+kev", "cves": ["CVE-2017-9841"], "name": "PHPUnit Command Injection Vulnerability", "severity": "CRITICAL"},
    ("php", "", "<7.1.33"): {"_source": "osv+kev", "cves": ["CVE-2019-11043"], "name": "PHP FastCGI Process Manager (FPM) Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("php", "", "<8.1.29"): {"_source": "osv+kev", "cves": ["CVE-2024-4577"], "name": "PHP-CGI OS Command Injection Vulnerability", "severity": "CRITICAL"},
    ("php", "", "<=1.1.1"): {"_source": "osv+kev", "cves": ["CVE-2019-9082"], "name": "ThinkPHP Remote Code Execution Vulnerability", "severity": "CRITICAL"},
    ("php", "", "<=1.3.0"): {"_source": "osv+kev", "cves": ["CVE-2018-20062"], "name": "ThinkPHP \"noneCms\" Remote Code Execution Vulnerability", "severity": "CRITICAL"},
    ("php", "", "<=1.6.1"): {"_source": "osv+kev", "cves": ["CVE-2019-9082"], "name": "ThinkPHP Remote Code Execution Vulnerability", "severity": "CRITICAL"},
    ("php", "", "<=12.04"): {"_source": "osv+kev", "cves": ["CVE-2019-11043"], "name": "PHP FastCGI Process Manager (FPM) Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("php", "", "<=14.04"): {"_source": "osv+kev", "cves": ["CVE-2019-11043"], "name": "PHP FastCGI Process Manager (FPM) Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("php", "", "<=3.6.5"): {"_source": "osv+kev", "cves": ["CVE-2016-10033"], "name": "PHPMailer Command Injection Vulnerability", "severity": "CRITICAL"},
    ("php", "", "<=4.7"): {"_source": "osv+kev", "cves": ["CVE-2016-10033"], "name": "PHPMailer Command Injection Vulnerability", "severity": "CRITICAL"},
    ("progress", "moveit", "<14.0.5.45"): {"_source": "osv+kev", "cves": ["CVE-2023-34362"], "name": "Progress MOVEit Transfer SQL Injection Vulnerability", "severity": "CRITICAL"},
    ("progress", "moveit", "<14.1.6.97"): {"_source": "osv+kev", "cves": ["CVE-2023-34362"], "name": "Progress MOVEit Transfer SQL Injection Vulnerability", "severity": "CRITICAL"},
    ("progress", "moveit", "<15.0.2.39"): {"_source": "osv+kev", "cves": ["CVE-2023-34362"], "name": "Progress MOVEit Transfer SQL Injection Vulnerability", "severity": "CRITICAL"},
    ("progress", "ws_ftp", "<8.7.4"): {"_source": "osv+kev", "cves": ["CVE-2023-40044"], "name": "Progress WS_FTP Server Deserialization of Untrusted Data Vulnerability", "severity": "CRITICAL"},
    ("progress", "ws_ftp", "<8.8.2"): {"_source": "osv+kev", "cves": ["CVE-2023-40044"], "name": "Progress WS_FTP Server Deserialization of Untrusted Data Vulnerability", "severity": "CRITICAL"},
    ("vmware", "esxi", "<3.10.1.2"): {"_source": "osv+kev", "cves": ["CVE-2020-3992"], "name": "VMware ESXi OpenSLP Use-After-Free Vulnerability", "severity": "CRITICAL"},
    ("vmware", "esxi", "<4.1.0.1"): {"_source": "osv+kev", "cves": ["CVE-2020-3992"], "name": "VMware ESXi OpenSLP Use-After-Free Vulnerability", "severity": "CRITICAL"},
    ("vmware", "esxi", "<5.2"): {"_source": "osv+kev", "cves": ["CVE-2024-37085"], "name": "VMware ESXi Authentication Bypass Vulnerability", "severity": "CRITICAL"},
    ("vmware", "esxi", "<9.0.0.0"): {"_source": "osv+kev", "cves": ["CVE-2019-5544"], "name": "VMware ESXi and Horizon DaaS OpenSLP Heap-Based Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("vmware", "esxi", "<=6.0-1"): {"_source": "osv+kev", "cves": ["CVE-2019-5544"], "name": "VMware ESXi and Horizon DaaS OpenSLP Heap-Based Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("vmware", "esxi", "<=6.0-NA"): {"_source": "osv+kev", "cves": ["CVE-2019-5544"], "name": "VMware ESXi and Horizon DaaS OpenSLP Heap-Based Buffer Overflow Vulnerability", "severity": "CRITICAL"},
    ("vmware", "esxi", "<=6.5-NA"): {"_source": "osv+kev", "cves": ["CVE-2020-3992"], "name": "VMware ESXi OpenSLP Use-After-Free Vulnerability", "severity": "CRITICAL"},
    ("vmware", "esxi", "<=7.0"): {"_source": "osv+kev", "cves": ["CVE-2024-37085"], "name": "VMware ESXi Authentication Bypass Vulnerability", "severity": "CRITICAL"},
    ("vmware", "esxi", "<=7.0-NA"): {"_source": "osv+kev", "cves": ["CVE-2025-22226", "CVE-2025-22225", "CVE-2025-22224"], "name": "VMware ESXi, Workstation, and Fusion Information Disclosure Vulnerability", "severity": "CRITICAL"},
    ("vmware", "esxi", "<=7.0-beta"): {"_source": "osv+kev", "cves": ["CVE-2025-22226", "CVE-2025-22225", "CVE-2025-22224"], "name": "VMware ESXi, Workstation, and Fusion Information Disclosure Vulnerability", "severity": "CRITICAL"},
    ("vmware", "esxi", "<=7.0-update_1"): {"_source": "osv+kev", "cves": ["CVE-2025-22226", "CVE-2025-22225", "CVE-2025-22224"], "name": "VMware ESXi, Workstation, and Fusion Information Disclosure Vulnerability", "severity": "CRITICAL"},
    ("vmware", "esxi", "<=8.0-NA"): {"_source": "osv+kev", "cves": ["CVE-2024-37085"], "name": "VMware ESXi Authentication Bypass Vulnerability", "severity": "CRITICAL"},
    ("vmware", "vcenter", "<3.10.1.2"): {"_source": "osv+kev", "cves": ["CVE-2021-21973", "CVE-2021-21972"], "name": "VMware vCenter Server and Cloud Foundation Server Side Request Forgery (SSRF) Vu", "severity": "CRITICAL"},
    ("vmware", "vcenter", "<3.11"): {"_source": "osv+kev", "cves": ["CVE-2022-22948"], "name": "VMware vCenter Server Incorrect Default File Permissions Vulnerability", "severity": "CRITICAL"},
    ("vmware", "vcenter", "<4.2"): {"_source": "osv+kev", "cves": ["CVE-2021-21973", "CVE-2021-21972"], "name": "VMware vCenter Server and Cloud Foundation Server Side Request Forgery (SSRF) Vu", "severity": "CRITICAL"},
    ("vmware", "vcenter", "<4.4.1"): {"_source": "osv+kev", "cves": ["CVE-2022-22948"], "name": "VMware vCenter Server Incorrect Default File Permissions Vulnerability", "severity": "CRITICAL"},
    ("vmware", "vcenter", "<5.0"): {"_source": "osv+kev", "cves": ["CVE-2021-22005"], "name": "VMware vCenter Server File Upload Vulnerability", "severity": "CRITICAL"},
    ("vmware", "vcenter", "<5.2"): {"_source": "osv+kev", "cves": ["CVE-2024-38813", "CVE-2024-38812"], "name": "VMware vCenter Server Privilege Escalation Vulnerability", "severity": "CRITICAL"},
    ("vmware", "vcenter", "<=5.5"): {"_source": "osv+kev", "cves": ["CVE-2023-34048"], "name": "VMware vCenter Server Out-of-Bounds Write Vulnerability", "severity": "CRITICAL"},
    ("vmware", "vcenter", "<=6.5-NA"): {"_source": "osv+kev", "cves": ["CVE-2022-22948", "CVE-2021-21973", "CVE-2021-22005", "CVE-2021-21972", "CVE-2021-21985"], "name": "VMware vCenter Server Incorrect Default File Permissions Vulnerability", "severity": "CRITICAL"},
    ("vmware", "vcenter", "<=6.5-a"): {"_source": "osv+kev", "cves": ["CVE-2021-21985"], "name": "VMware vCenter Server Improper Input Validation Vulnerability", "severity": "CRITICAL"},
    ("vmware", "vcenter", "<=6.5-b"): {"_source": "osv+kev", "cves": ["CVE-2021-21985"], "name": "VMware vCenter Server Improper Input Validation Vulnerability", "severity": "CRITICAL"},
    ("vmware", "vcenter", "<=6.7-NA"): {"_source": "osv+kev", "cves": ["CVE-2021-22017", "CVE-2021-22005", "CVE-2020-3952"], "name": "VMware vCenter Server Improper Access Control", "severity": "CRITICAL"},
    ("vmware", "vcenter", "<=7.0-NA"): {"_source": "osv+kev", "cves": ["CVE-2024-38813", "CVE-2024-38812", "CVE-2023-34048"], "name": "VMware vCenter Server Privilege Escalation Vulnerability", "severity": "CRITICAL"},
    ("vmware", "vcenter", "<=7.0-a"): {"_source": "osv+kev", "cves": ["CVE-2024-38813", "CVE-2024-38812", "CVE-2023-34048"], "name": "VMware vCenter Server Privilege Escalation Vulnerability", "severity": "CRITICAL"},
}
